services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags: ['command']
    
    PhpOrchestra\Cli\:
        resource: '../src/'
    PhpOrchestra\Cli\Application: 
        arguments:
            - !tagged command
    
    PhpOrchestra\Cli\Commands\Solution\InitializeCommand:
        arguments: 
            - '@PhpOrchestra\Application\Handler\InitializeSolutionHandler'

    PhpOrchestra\Application\Handler\InitializeSolutionHandler: ~


        