services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags: ['command']
    
    PhpOrchestra\Cli\:
        resource: '../src/'
    PhpOrchestra\Cli\Application: 
        arguments:
            - !tagged command

    PhpOrchestra\Cli\Commands\Project\AddReferenceCommand:
        arguments:
            - '@PhpOrchestra\Application\Adapter\SolutionAdapter'
            - '@PhpOrchestra\Application\Facade\ProjectScanner'
            - '@PhpOrchestra\Application\Handler\AddProjectReferenceHandler'
    
    PhpOrchestra\Cli\Commands\Solution\InitializeCommand:
        arguments: 
            - '@PhpOrchestra\Application\Handler\InitializeSolutionHandler'
    
    PhpOrchestra\Cli\Commands\Solution\AddProjectCommand:
        arguments: 
            - '@PhpOrchestra\Application\Handler\AddProjectToSolutionHandler'
            - '@PhpOrchestra\Application\Adapter\SolutionAdapter'

    PhpOrchestra\Cli\Commands\Solution\RemoveProjectCommand:
        arguments:
            - '@PhpOrchestra\Application\Handler\RemoveProjectFromSolutionHandler'
            - '@PhpOrchestra\Application\Adapter\SolutionAdapter'
            - '@PhpOrchestra\Application\Facade\ProjectScanner'

    PhpOrchestra\Cli\Commands\Solution\InstallDependenciesCommand:
        arguments:
            - '@PhpOrchestra\Application\Handler\InstallSolutionDependenciesHandler'
            - '@PhpOrchestra\Application\Adapter\SolutionAdapter'

    PhpOrchestra\Application\Handler\InitializeSolutionHandler:
        arguments:
          - '@PhpOrchestra\Application\Facade\ProjectScanner'
          - '@PhpOrchestra\Application\Adapter\SolutionAdapter'
    
    PhpOrchestra\Application\Handler\AddProjectToSolutionHandler:
        arguments:
          - '@PhpOrchestra\Application\Facade\ProjectScanner'
          - '@PhpOrchestra\Application\Adapter\SolutionAdapter'    
    
    PhpOrchestra\Application\Handler\InstallSolutionDependenciesHandler: ~

    PhpOrchestra\Application\Handler\RemoveProjectFromSolutionHandler:
        arguments:
            - '@PhpOrchestra\Application\Adapter\SolutionAdapter'

    PhpOrchestra\Application\Handler\AddProjectReferenceHandler: ~

    PhpOrchestra\Application\Facade\ProjectScanner:
        arguments:
          - '@PhpOrchestra\Application\Adapter\ComposerAdapter'
    
    PhpOrchestra\Application\Adapter\ComposerAdapter: ~
    PhpOrchestra\Application\Adapter\SolutionAdapter: 
        arguments:
            - '@PhpOrchestra\Application\Builder\SolutionBuilder'
    PhpOrchestra\Application\Builder\SolutionBuilder:
        arguments:
            - '@PhpOrchestra\Application\Builder\ProjectBuilder'
    
    PhpOrchestra\Application\Builder\ProjectBuilder: ~

        